# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/repo/CVE_DataMining_Research

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/repo/CVE_DataMining_Research

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/repo/CVE_DataMining_Research/CMakeFiles /mnt/c/repo/CVE_DataMining_Research/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/repo/CVE_DataMining_Research/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Stats

# Build rule for target.
Stats: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Stats
.PHONY : Stats

# fast build rule for target.
Stats/fast:
	$(MAKE) -f CMakeFiles/Stats.dir/build.make CMakeFiles/Stats.dir/build
.PHONY : Stats/fast

src/JsonHelper.o: src/JsonHelper.cpp.o

.PHONY : src/JsonHelper.o

# target to build an object file
src/JsonHelper.cpp.o:
	$(MAKE) -f CMakeFiles/Stats.dir/build.make CMakeFiles/Stats.dir/src/JsonHelper.cpp.o
.PHONY : src/JsonHelper.cpp.o

src/JsonHelper.i: src/JsonHelper.cpp.i

.PHONY : src/JsonHelper.i

# target to preprocess a source file
src/JsonHelper.cpp.i:
	$(MAKE) -f CMakeFiles/Stats.dir/build.make CMakeFiles/Stats.dir/src/JsonHelper.cpp.i
.PHONY : src/JsonHelper.cpp.i

src/JsonHelper.s: src/JsonHelper.cpp.s

.PHONY : src/JsonHelper.s

# target to generate assembly for a file
src/JsonHelper.cpp.s:
	$(MAKE) -f CMakeFiles/Stats.dir/build.make CMakeFiles/Stats.dir/src/JsonHelper.cpp.s
.PHONY : src/JsonHelper.cpp.s

src/stats.o: src/stats.cpp.o

.PHONY : src/stats.o

# target to build an object file
src/stats.cpp.o:
	$(MAKE) -f CMakeFiles/Stats.dir/build.make CMakeFiles/Stats.dir/src/stats.cpp.o
.PHONY : src/stats.cpp.o

src/stats.i: src/stats.cpp.i

.PHONY : src/stats.i

# target to preprocess a source file
src/stats.cpp.i:
	$(MAKE) -f CMakeFiles/Stats.dir/build.make CMakeFiles/Stats.dir/src/stats.cpp.i
.PHONY : src/stats.cpp.i

src/stats.s: src/stats.cpp.s

.PHONY : src/stats.s

# target to generate assembly for a file
src/stats.cpp.s:
	$(MAKE) -f CMakeFiles/Stats.dir/build.make CMakeFiles/Stats.dir/src/stats.cpp.s
.PHONY : src/stats.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Stats"
	@echo "... src/JsonHelper.o"
	@echo "... src/JsonHelper.i"
	@echo "... src/JsonHelper.s"
	@echo "... src/stats.o"
	@echo "... src/stats.i"
	@echo "... src/stats.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

